# Generated by Django 6.0.7 on 2026-08-07 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='titulo')),
                ('category', models.CharField(max_length=60, verbose_name='categoria')),
                ('image_url', models.URLField(max_length=500, verbose_name='imagem')),
                ('prep_time', models.PositiveIntegerField(verbose_name='tempo de preparo (minutos)')),
                ('difficulty', models.CharField(default='Fácil', max_length=20, verbose_name='dificuldade')),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=2, verbose_name='avaliação')),
                ('is_featured', models.BooleanField(default=True, verbose_name='em destaque')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'receita',
                'verbose_name_plural': 'receitas',
                'ordering': ['-created_at', '-rating', 'title'],
            },
        ),
    ]
